// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// resample_files_double
void resample_files_double(const std::string& from, int fromStride, int fromRows, int fromCols, const std::string& to, int toStride, int toRows, int toCols, const std::string& method);
RcppExport SEXP rasterfaster_resample_files_double(SEXP fromSEXP, SEXP fromStrideSEXP, SEXP fromRowsSEXP, SEXP fromColsSEXP, SEXP toSEXP, SEXP toStrideSEXP, SEXP toRowsSEXP, SEXP toColsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type fromStride(fromStrideSEXP);
    Rcpp::traits::input_parameter< int >::type fromRows(fromRowsSEXP);
    Rcpp::traits::input_parameter< int >::type fromCols(fromColsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type to(toSEXP);
    Rcpp::traits::input_parameter< int >::type toStride(toStrideSEXP);
    Rcpp::traits::input_parameter< int >::type toRows(toRowsSEXP);
    Rcpp::traits::input_parameter< int >::type toCols(toColsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    resample_files_double(from, fromStride, fromRows, fromCols, to, toStride, toRows, toCols, method);
    return R_NilValue;
END_RCPP
}
