# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

resample_files_numeric <- function(from, fromStride, fromRows, fromCols, to, toStride, toRows, toCols, dataFormat, method) {
    invisible(.Call('rasterfaster_resample_files_numeric', PACKAGE = 'rasterfaster', from, fromStride, fromRows, fromCols, to, toStride, toRows, toCols, dataFormat, method))
}

