# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doFindMode <- function(x) {
    .Call('rasterfaster_doFindMode', PACKAGE = 'rasterfaster', x)
}

findMean <- function(x) {
    .Call('rasterfaster_findMean', PACKAGE = 'rasterfaster', x)
}

doColorRamp <- function(colors, x, alpha, naColor) {
    .Call('rasterfaster_doColorRamp', PACKAGE = 'rasterfaster', colors, x, alpha, naColor)
}

rgbToLab <- function(rgb) {
    .Call('rasterfaster_rgbToLab', PACKAGE = 'rasterfaster', rgb)
}

rgbToXyz <- function(rgb) {
    .Call('rasterfaster_rgbToXyz', PACKAGE = 'rasterfaster', rgb)
}

doMipmap <- function(x, dx) {
    .Call('rasterfaster_doMipmap', PACKAGE = 'rasterfaster', x, dx)
}

do_project <- function(name, from, fromStride, fromRows, fromCols, lng1, lng2, lat1, lat2, to, toStride, toRows, toCols, x, y, totalWidth, totalHeight, dataFormat, method) {
    invisible(.Call('rasterfaster_do_project', PACKAGE = 'rasterfaster', name, from, fromStride, fromRows, fromCols, lng1, lng2, lat1, lat2, to, toStride, toRows, toCols, x, y, totalWidth, totalHeight, dataFormat, method))
}

resample_files_numeric <- function(from, fromStride, fromRows, fromCols, to, toStride, toRows, toCols, dataFormat, method) {
    invisible(.Call('rasterfaster_resample_files_numeric', PACKAGE = 'rasterfaster', from, fromStride, fromRows, fromCols, to, toStride, toRows, toCols, dataFormat, method))
}

