# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the mode for a vector
#'
#' Calculates the mode for integer, real, character, and logical vectors. In
#' the event of a tie, a winner is chosen at random (using C's \code{rand()},
#' so not affected by \code{\link[base:set.seed]{set.seed()}}, sorry!).
#'
#' @param x An integer, real, character, or logical vector
#'
#' @seealso Intended to be a faster, less flexible replacement for
#'   \code{\link[raster:modal]{raster::modal}}.
#'
#' @export
findMode <- function(x) {
    .Call('rasterfaster_findMode', PACKAGE = 'rasterfaster', x)
}

#' @export
findMean <- function(x) {
    .Call('rasterfaster_findMean', PACKAGE = 'rasterfaster', x)
}

do_project <- function(name, from, fromStride, fromRows, fromCols, lng1, lng2, lat1, lat2, to, toStride, toRows, toCols, x, y, totalWidth, totalHeight, dataFormat, method) {
    invisible(.Call('rasterfaster_do_project', PACKAGE = 'rasterfaster', name, from, fromStride, fromRows, fromCols, lng1, lng2, lat1, lat2, to, toStride, toRows, toCols, x, y, totalWidth, totalHeight, dataFormat, method))
}

resample_files_numeric <- function(from, fromStride, fromRows, fromCols, to, toStride, toRows, toCols, dataFormat, method) {
    invisible(.Call('rasterfaster_resample_files_numeric', PACKAGE = 'rasterfaster', from, fromStride, fromRows, fromCols, to, toStride, toRows, toCols, dataFormat, method))
}

